# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Siddharth Kumar - Portfolio and Blog 
email: sidkuma24@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  A website that contains my blogs and my projects and research
  on deep learning its various  applications in computer vision 
  and natural language processing.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "sidkuma24.github.com" # the base hostname & protocol for your site, e.g. http://example.com

# Author settings
author: Siddharth Kumar # add your name
author-pic: 
about-author: I am a 2nd Semester Computer Science Masters Student at San Jose State University. I have spent most of my time here building web application using JavaScript and applying deep learning in my projects.



twitter_username: sidkuma24
github_username:  sikduma24

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap

# future: true
# kramdown:
#   parse_block_html: true
#   syntax_highlighter: rouge
# permalink: pretty
#paginate: 5

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md
  - bower_components
  - .travis.yml